sudo: required
services:
  - docker

before_install:
  - docker build -t basavabalte/docker-react -f Dockerfile.dev .

script:
  -  docker run -e CI=true basavabalte/docker-react npm run test -- --coverage 

deploy: 
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-227796619437"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$SECRET_ACCESS_KEY"